version: '3.9'

services:
  postgres1:
    image: postgres:13
    environment:
      POSTGRES_DB: replica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres4_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    container_name: auth
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres1:
        condition: service_healthy

volumes:
  postgres4_data: